### ISSUE TITLE
`print` v. `echo`

### ISSUE THREAD

**Issue by mdawaffe** [flaviovs/vault#4]
In most places, I see `echo`.

[Here](https://github.com/flaviovs/vault/blob/5455673be8e1f7f19aa7bfe7eaac9b90a60f420f/view/unlock-view.php#L3) is a `print` statement.

When should we use which?

**Comment by flaviovs** [comment]
We should always use `echo`. The difference between the two is subtle, but for consistency (incl. consistency with other A8c products), `echo` is preferable.

I still find myself occasionally typing `print` because when I started using PHP a long time ago, `print` was the natural way to me (coming from C's `printf`), but for quite some time now I am trying to stick with `echo`.
