### ISSUE TITLE
Schema Questions

### ISSUE THREAD

**Issue by mdawaffe** [flaviovs/vault#8]
## References

I don't think MySQL accepts `REFERENCES` outside of `FOREIGN KEY` statements.  Can you look into this?
https://github.com/flaviovs/vault/blob/5455673be8e1f7f19aa7bfe7eaac9b90a60f420f/lib/schema.php#L22
## LogLevel

Is this table necessary? Seems like it might be over-normalization.

**Comment by flaviovs** [comment]
>  I don't think MySQL accepts REFERENCES outside of FOREIGN KEY statements

It doesn't. And I was bitten by this before:  334d5f8192af91031ec0c7652e62b933020818b9

And it does even care to issue a warning message. :expressionless: 

> LogLevel / Is this table necessary? Seems like it might be over-normalization.

The goal here is to leverage the DB to ensure consistency. This come at a price (i.e., you need an auxiliary table).

If it was in PostgreSQL, I could use a `CHECK` constraint in the "log level" column (log table), so that it would accept only valid values. Unfortunately, MySQL still doesn't support `CHECK` constraints, so a foreign key is a good workaround. (We could use triggers, but they're more exotic and difficult to understand than "another table" -- and at the end of the day it will be another db object anyway).

**Comment by flaviovs** [comment]
BTW, out of curiosity... do you use PostgreSQL in any project?

**Comment by mdawaffe** [comment]
> BTW, out of curiosity... do you use PostgreSQL in any project?

Nope.
